server:
  port: 7777
  
#指定应用名称(Application)推荐使用小写,注册中心默认大写
spring:
  application:
    name: provider

#EurekaClient基本配置
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
      #defaultZone: http://admin:admin@localhost:8761/eureka,http://admin:admin@localhost:8762/eureka
#服务实例配置IP访问
  instance:
    prefer-ip-address: true
#服务实例名称配置(应用名称：端口)
    instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${spring.application.instance_id:${server.port}}
    #元数据
    #metadata-map:
      #zone: youzuca
