server:
  port: 8888
  #context-path: /consumer
  
#指定应用名称
spring:
  application:
    name: consumer

#EurekaClient基本配置
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
      #defaultZone: http://admin:admin@localhost:8761/eureka,http://admin:admin@localhost:8762/eureka
  instance:
    prefer-ip-address: true
    #home-page-url-path: /consumer
#服务实例名称配置(应用名称：端口)
    instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${spring.application.instance_id:${server.port}}
    
#Feign日志级别
logging:
  level: 
    com.akko.feign.UserClient: DEBUG

#hystrix 超时设置
#hystrix.command.HystrixCommandKey.execution.isolation.thread.timeoutInMillisecond: 3000
#hystrix.command.default.execution.timeout.enabled: false 
feign.hystrix.enabled: true
